[project]
name = "redArrow"
version = "3.1.1"
description = "Outline checker for Glyphs"
readme = "README.md"
requires-python = ">=3.11"
authors = [{ name = "Jens Kutílek", email = "webmail@kutilek.de" }]

dependencies = [
  "pyobjc",
]

[dependency-groups]
dev = [
  "mypy >= 2.4.0",
  "ruff >= 0.16.10",
]
test = [
  "pytest-cov >= 7.1.0",
  "pytest >= 9.1.1",
  "tox-gh >= 1.8.0",
  "tox-uv >= 1.36.1",
  "tox >= 4.64.9",
  { include-group = "dev" },
]

[build-system]
requires = ["uv_build>=0.12.23,<0.13"]
build-backend = "uv_build"

[tool.ruff.lint]
future-annotations = false
ignore = ["N999"]

[tool.ruff.lint.isort]
known-first-party = ["redArrow"]

[tool.uv.build-backend]
module-name = "redArrow"
module-root = "RedArrow.glyphsReporter/Contents/Resources"
